# https://gleam.run/writing-gleam/gleam-toml/.

name = "search_algorithms_gleam"
version = "0.1.0"
description = "A collection of common Search Algorithms"

licences = ["Apache-2.0"]
repository = { type = "github", user = "harris-miller", repo = "gleam_search_algorithms" }

target = "erlang"

internal_modules = ["internal/*"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_deque = ">= 1.0.0 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
balanced_tree_gleam = ">= 0.1.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
